# Generated by Django 4.2.13 on 2024-06-14 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text="Identifier of the project; used in IRIs for the project's RDF data", max_length=64, unique=True)),
                ('display_name', models.CharField(help_text='Human-friendly name for the project', max_length=256)),
                ('summary', models.TextField(blank=True, help_text='Summary of the project')),
                ('public', models.BooleanField(default=False, help_text='If true, any visitors can read the RDF data in this project')),
                ('groups', models.ManyToManyField(blank=True, help_text='User groups with write access to this project; all their members will gain access.', related_name='projects', to='auth.group')),
                ('users', models.ManyToManyField(blank=True, help_text='Users who can write RDF data in this project', related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
