# Generated by Django 4.2.13 on 2024-06-17 12:49

from django.db import migrations
import re


def name_to_slug(name: str, max_length: int = 64) -> str:
    lowercase = name.lower()
    no_whitespace = re.sub(r'\s', '_', lowercase)
    cleaned = re.sub(r'[^a-z_]', '', no_whitespace)
    return cleaned[:min(max_length, len(cleaned))]


def research_groups_to_projects(apps, schema_editor):
    ResearchGroup = apps.get_model('vre', 'ResearchGroup')
    Project = apps.get_model('projects', 'Project')

    for research_group in ResearchGroup.objects.all():
        project = Project.objects.create(
            name=name_to_slug(research_group.name),
            display_name=research_group.name,
        )
        for user in research_group.members.all():
            project.users.add(user)
        project.save()


class Migration(migrations.Migration):
    '''
    Migrate ResearchGroup data into Project table
    '''

    dependencies = [
        ('projects', '0001_initial'),
        ('vre', '0005_alter_annotation_content_alter_annotation_id_and_more')
    ]

    operations = [
        migrations.RunPython(
            research_groups_to_projects,
            reverse_code=migrations.RunPython.noop,
        )
    ]
