# Generated by Django 4.2.13 on 2024-07-02 13:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_researchgroups_to_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uri',
            field=models.CharField(blank=True, help_text='URI for the project in RDF data', max_length=256),
        ),
    ]
