# Generated by Django 4.2.13 on 2024-07-02 13:01

from django.db import migrations
from projects.signals import set_project_uri

def fill_project_uri(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')

    for project in Project.objects.all():
        set_project_uri(Project, project)
        project.save()

def clear_project_uri(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')

    for project in Project.objects.all():
        project.uri = ''
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_uri'),
    ]

    operations = [
        migrations.RunPython(fill_project_uri, reverse_code=clear_project_uri)
    ]
