# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 14:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='annotation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
