# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 10:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vre', '0002_auto_20180314_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default='VRE Annotation')),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='annotation',
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='VRE Record'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='members',
            field=models.ManyToManyField(related_name='researchgroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='managing_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vre.ResearchGroup'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vre.Record'),
        ),
    ]
