# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-05 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vre', '0003_auto_20180322_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='uri',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
